title: Personal Site
url: https://agneselombardi.github.io
lang: en

# description: >
#   I'm a PhD student at the Department of Philology, Literature, and Linguistics of the University of Pisa and a member of the CoLing Lab.
#   Although from November to April you can find me at UT Texas Austin as a visiting scholar.
#   My supervisors are Alessandro Lenci and Domenica Romagno.

# Build settings

# Use the latest version of Minima from GitHub Pages
# Comment out if you want to stick with Minima 2.5.1
remote_theme: jekyll/minima
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you have collections, ensure they are properly configured:
collections:
  publications:
    output: true

# Optional: Link specific pages in your header
# header_pages:
#   - index.md

# Minima-specific settings (for 3.0+)
minima:
  skin: classic
  # date_format: "%b %d, %Y"

  social_links:
    - { platform: github,         user_url: "https://github.com/agneselombardi" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=cDhHLS4AAAAJ&hl=it" }
    - { platform: x,              user_url: "https://x.com/AgneseLombardi" }
